/**
 * lib/constants.ts
 * Category metadata, freshness options, mock articles, and mock sources.
 * MOCK DATA — replace API calls with real endpoints when backend is connected.
 */
import type { CategorySlug, FreshnessWindow } from "@/types";

// ── Category metadata ─────────────────────────────────────────────────────────

export const CATEGORY_META: Record<
  CategorySlug,
  { label: string; emoji: string; description: string }
> = {
  ai:         { label: "AI & ML",     emoji: "🤖", description: "Artificial intelligence, machine learning, and foundation models" },
  technology: { label: "Technology",  emoji: "💻", description: "Software, hardware, cybersecurity, and the digital world" },
  education:  { label: "Education",   emoji: "📚", description: "Universities, EdTech, policy, and global learning" },
  politics:   { label: "Politics",    emoji: "🏛️", description: "Governments, elections, policy, and geopolitics" },
  business:   { label: "Business",    emoji: "📈", description: "Markets, finance, economy, and corporate news" },
  startups:   { label: "Startups",    emoji: "🚀", description: "Venture capital, funding rounds, and founders" },
  world:      { label: "World",       emoji: "🌍", description: "International affairs, conflicts, and diplomacy" },
  sports:     { label: "Sports",      emoji: "⚽", description: "Football, cricket, basketball, tennis, and more" },
  health:     { label: "Health",      emoji: "🏥", description: "Medicine, research, public health, and science" },
};

export const ALL_CATEGORIES = Object.keys(CATEGORY_META) as CategorySlug[];

export const FRESHNESS_OPTIONS: { label: string; value: FreshnessWindow }[] = [
  { label: "Last 6h",  value: 6  },
  { label: "Last 24h", value: 24 },
  { label: "Last 48h", value: 48 },
];

// ── Mock articles ─────────────────────────────────────────────────────────────
// MOCK — used when NEXT_PUBLIC_API_URL is unreachable (demo mode)

export const MOCK_ARTICLES = [
  {
    id: "1",
    title: "UN Security Council passes landmark AI governance resolution",
    summary: "The United Nations Security Council unanimously adopted a resolution establishing international AI safety standards, calling for mandatory evaluations of frontier models and creating a new oversight body to monitor compliance across member states.",
    category: "politics" as CategorySlug,
    source_name: "Associated Press",
    source_url: "https://apnews.com",
    canonical_url: "#",
    image_url: null,
    author: "Sarah Chen",
    published_at: new Date(Date.now() - 8 * 60000).toISOString(),
    credibility_score: 0.95,
    freshness_score: 0.98,
    composite_score: 0.96,
    fact_check_status: "clear" as const,
    is_breaking: true,
    is_cluster_representative: true,
    duplicate_cluster_id: "c-1",
    cluster_source_count: 6,
    tags: ["UN", "AI Policy", "Governance"],
  },
  {
    id: "2",
    title: "Anthropic releases Claude 4 with extended multi-step reasoning",
    summary: "Anthropic unveiled Claude 4, featuring breakthrough extended reasoning capabilities that allow complex multi-step problem solving across mathematics, coding, and scientific analysis benchmarks.",
    category: "ai" as CategorySlug,
    source_name: "MIT Technology Review",
    source_url: "https://technologyreview.com",
    canonical_url: "#",
    image_url: null,
    author: "James Liu",
    published_at: new Date(Date.now() - 34 * 60000).toISOString(),
    credibility_score: 0.92,
    freshness_score: 0.94,
    composite_score: 0.93,
    fact_check_status: "clear" as const,
    is_breaking: false,
    is_cluster_representative: true,
    duplicate_cluster_id: "c-2",
    cluster_source_count: 9,
    tags: ["AI", "Anthropic", "Claude"],
  },
  {
    id: "3",
    title: "Federal Reserve signals rate cut as inflation cools to 2.1%",
    summary: "The Federal Reserve hinted at a rate reduction in coming months as inflation data showed consistent progress toward its 2% target. Markets rallied sharply on the news.",
    category: "business" as CategorySlug,
    source_name: "Bloomberg",
    source_url: "https://bloomberg.com",
    canonical_url: "#",
    image_url: null,
    author: "Michael Torres",
    published_at: new Date(Date.now() - 68 * 60000).toISOString(),
    credibility_score: 0.90,
    freshness_score: 0.87,
    composite_score: 0.89,
    fact_check_status: "clear" as const,
    is_breaking: false,
    is_cluster_representative: true,
    duplicate_cluster_id: "c-3",
    cluster_source_count: 7,
    tags: ["Fed", "Finance", "Markets"],
  },
  {
    id: "4",
    title: "OpenAI and Microsoft expand partnership with $10B enterprise deal",
    summary: "Microsoft and OpenAI announced an expanded $10 billion partnership targeting enterprise AI deployment, including exclusive Azure integration for the upcoming GPT-5 model.",
    category: "startups" as CategorySlug,
    source_name: "TechCrunch",
    source_url: "https://techcrunch.com",
    canonical_url: "#",
    image_url: null,
    author: "Priya Patel",
    published_at: new Date(Date.now() - 122 * 60000).toISOString(),
    credibility_score: 0.85,
    freshness_score: 0.85,
    composite_score: 0.85,
    fact_check_status: "clear" as const,
    is_breaking: false,
    is_cluster_representative: true,
    duplicate_cluster_id: "c-4",
    cluster_source_count: 5,
    tags: ["OpenAI", "Microsoft", "Enterprise"],
  },
  {
    id: "5",
    title: "WHO reports 40% decline in malaria deaths over the past decade",
    summary: "The World Health Organization published findings showing a 40% reduction in malaria deaths, attributing the progress to artemisinin-based therapies and improved bed net coverage across sub-Saharan Africa.",
    category: "health" as CategorySlug,
    source_name: "Reuters",
    source_url: "https://reuters.com",
    canonical_url: "#",
    image_url: null,
    author: "Dr. Amara Osei",
    published_at: new Date(Date.now() - 183 * 60000).toISOString(),
    credibility_score: 0.96,
    freshness_score: 0.80,
    composite_score: 0.90,
    fact_check_status: "clear" as const,
    is_breaking: false,
    is_cluster_representative: true,
    duplicate_cluster_id: "c-5",
    cluster_source_count: 4,
    tags: ["WHO", "Health", "Africa"],
  },
  {
    id: "6",
    title: "Global Education Summit pledges $50B for digital literacy by 2030",
    summary: "Leaders at the Geneva summit agreed on a framework committing $50 billion across 120 countries for universal digital literacy programs targeting underserved communities.",
    category: "education" as CategorySlug,
    source_name: "BBC News",
    source_url: "https://bbc.com",
    canonical_url: "#",
    image_url: null,
    author: "Elena Marchetti",
    published_at: new Date(Date.now() - 241 * 60000).toISOString(),
    credibility_score: 0.95,
    freshness_score: 0.76,
    composite_score: 0.87,
    fact_check_status: "clear" as const,
    is_breaking: false,
    is_cluster_representative: true,
    duplicate_cluster_id: "c-6",
    cluster_source_count: 3,
    tags: ["Education", "UN", "Digital"],
  },
  {
    id: "7",
    title: "India defeats Australia to win ICC Cricket World Cup",
    summary: "India claimed the ICC Cricket World Cup title with a decisive 6-wicket victory over Australia at Wankhede Stadium, completing an unbeaten run through the entire tournament.",
    category: "sports" as CategorySlug,
    source_name: "ESPN",
    source_url: "https://espn.com",
    canonical_url: "#",
    image_url: null,
    author: "Rahul Sharma",
    published_at: new Date(Date.now() - 302 * 60000).toISOString(),
    credibility_score: 0.85,
    freshness_score: 0.73,
    composite_score: 0.80,
    fact_check_status: "clear" as const,
    is_breaking: false,
    is_cluster_representative: true,
    duplicate_cluster_id: "c-7",
    cluster_source_count: 11,
    tags: ["Cricket", "ICC", "India"],
  },
  {
    id: "8",
    title: "IBM reaches 1,000-qubit stability milestone in quantum computing",
    summary: "Researchers at IBM demonstrated stable operation of a 1,000-qubit quantum processor, marking a critical step toward practical quantum advantage in logistics and pharmaceutical research.",
    category: "technology" as CategorySlug,
    source_name: "Wired",
    source_url: "https://wired.com",
    canonical_url: "#",
    image_url: null,
    author: "Chris Weber",
    published_at: new Date(Date.now() - 310 * 60000).toISOString(),
    credibility_score: 0.87,
    freshness_score: 0.70,
    composite_score: 0.80,
    fact_check_status: "clear" as const,
    is_breaking: false,
    is_cluster_representative: true,
    duplicate_cluster_id: "c-8",
    cluster_source_count: 4,
    tags: ["Quantum", "IBM", "Research"],
  },
];

// ── Mock sources ──────────────────────────────────────────────────────────────
// MOCK — replace with sourcesApi.list() when backend is connected

export const MOCK_SOURCES = [
  { name: "Associated Press", domain: "apnews.com",           category: "General",    credibility_score: 0.95, article_count: 42 },
  { name: "Reuters",          domain: "reuters.com",          category: "General",    credibility_score: 0.96, article_count: 38 },
  { name: "BBC News",         domain: "bbc.com",              category: "General",    credibility_score: 0.93, article_count: 31 },
  { name: "Bloomberg",        domain: "bloomberg.com",        category: "Business",   credibility_score: 0.90, article_count: 27 },
  { name: "MIT Tech Review",  domain: "technologyreview.com", category: "Technology", credibility_score: 0.92, article_count: 19 },
  { name: "TechCrunch",       domain: "techcrunch.com",       category: "Technology", credibility_score: 0.85, article_count: 24 },
  { name: "The Guardian",     domain: "theguardian.com",      category: "General",    credibility_score: 0.88, article_count: 22 },
  { name: "Wired",            domain: "wired.com",            category: "Technology", credibility_score: 0.87, article_count: 17 },
  { name: "Financial Times",  domain: "ft.com",               category: "Business",   credibility_score: 0.91, article_count: 15 },
  { name: "ESPN",             domain: "espn.com",             category: "Sports",     credibility_score: 0.85, article_count: 14 },
  { name: "Al Jazeera",       domain: "aljazeera.com",        category: "World",      credibility_score: 0.82, article_count: 18 },
  { name: "NPR",              domain: "npr.org",              category: "General",    credibility_score: 0.90, article_count: 20 },
];